### PR TITLE
Add an example demonstrating a custom spinner and Tokio

### PR DESCRIPTION
**Pull request by silvioprog**

### CODE REVIEW

**Comment by silvioprog** [comment]
Example running on Ubuntu:

Peek 2021-09-11 02-13

**Comment by silvioprog** [comment]
Any change to apply this example? 😅

**Comment by djc** [comment]
3 days is a little soon to ping again IMO -- I'm just a volunteer maintaining this.

As for the change itself, I think indicatif already has a lot of examples, and in particular it already has a tokio example and a spinner example. So adding this as yet another example would not seem to be an improvement to me -- it just clutters up the examples directory even more.

**Comment by djc** [comment]
Going to close this for now.

**Pull request closed without merging**
