### PR TITLE
Add `contents_formatted` to `InMemoryTerm`

### PR DESCRIPTION
**Pull request by dfaust**
This method is almost identical to `contents`, but it includes VT-100 codes.

image

### CODE REVIEW

**Comment by djc** [comment]
Why do you need this?

**Comment by dfaust** [comment]
For testing. This allows seeing the colored output directly in the tests.

**Review by djc — COMMENTED** [review]
Sorry for being so slow to follow-up. Adding this API seems reasonable, though I'd prefer to add it in a way that doesn't duplicate as much code. How about we move most of the logic into a new `InMemoryTermState::contents()` method which can take a `formatted: bool` argument?

**Comment by dfaust** [comment]
I just pushed an updated version, which adds a reset code at the end of each line.
This is necessary because `rows_formatted` returns each line in an "undefined state".

Yes, there is some code duplication, the problem is, that `contents` returns a String, while `contents_formatted` returns a Vec<u8>. And this starts basically with the first call, since `rows` returns a String and `rows_formatted` returns a Vec<u8>.

One way would be for the `contents` method to turn the strings into vecs, process them and at the end turn the result vec back into a string.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Okay, thanks!

**Pull request merged**
