### PR TITLE
Bump version to 0.17.0

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by chris-laplante — APPROVED** [review]

**Comment by LingMan** [comment]
This version doesn't show up on crates.io and on the Github [releases page](https://github.com/console-rs/indicatif/releases) it shows [0.17.0-rc.11](https://github.com/console-rs/indicatif/releases/tag/0.17.0-rc.11) as being released yesterday. Did something go wrong, or am I not aware of something?

**Comment by djc** [comment]
I have not published it to crates.io yet. Will do that soon, but would like to merge #450 first.

**Comment by chris-laplante** [comment]
> I have not published it to crates.io yet. Will do that soon, but would like to merge #450 first.

Do you need me to approve it?

**Comment by LingMan** [comment]
Ah, that explains it.

**Pull request merged**
