### PR TITLE
Robustness

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by chris-laplante — APPROVED** [review]
LGTM since the other change I suggested is being worked on in #406

**Comment by djc** [comment]
@chris-laplante BTW, what timezone are you in?

**Comment by chris-laplante** [comment]
> @chris-laplante BTW, what timezone are you in?

EST. You?

**Comment by djc** [comment]
Usually on CET, until Thursday I'm on Pacific time though.

**Comment by chris-laplante** [comment]
Unfortunately my day was consumed by errands and personal matters, rather than Rust, but I hope to spend the next few hours tinkering.

**Pull request merged**
