### PR TITLE
Use `portable-atomic` to fix build on some 32-bit platforms

### LINKED ISSUE #475: Error compiling on armv5tel architecture
Hi, totally a rust noob so I apologize if I'm misreading what the rust compiler is telling me.
I'm trying to build homeassistant on an embedded armv5tel NAS (32-bit). I'm stuck at building maturin, which requires indicatif v0.17.0. While building, I get the following error:

```
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> /home/homeassistant/.cargo/registry/src/github.com-1285ae84e5963aae/indicatif-0.17.0/src/state.rs:2:25
  |
2 | use std::sync::atomic::{AtomicU64, AtomicU8, Ordering};
  |                         ^^^^^^^^^
  |                         |
  |                         no `AtomicU64` in `sync::atomic`
  |                         help: a similar name exists in the module: `AtomicU8`

For more information about this error, try `rustc --explain E0432`.
error: failed to compile `maturin v0.13.2 (/home/homeassistant/maturin)`, intermediate artifacts can be found at `/home/homeassistant/maturin/target`

Caused by:
  could not compile `indicatif` due to previous error
```

Some info about my environment:

```
(homeassistant) homeassistant@nsa325:~/maturin$ rustc --version
rustc 1.59.0
(homeassistant) homeassistant@nsa325:~/maturin$ cargo --version
cargo 1.56.0
(homeassistant) homeassistant@nsa325:~/maturin$ uname -a
Linux nsa325 5.15.5-kirkwood-tld-1 #1.0 PREEMPT Sun Nov 28 23:08:13 PST 2021 armv5tel GNU/Linux
(homeassistant) homeassistant@nsa325:~/maturin$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

It seems like `AtomicU64` is not defined on all architectures (I've seen similar reports for PowerPC, i.e. https://github.com/tikv/rust-prometheus/issues/315). Can you please provide a fix/workaround?

### PR DESCRIPTION
**Pull request by messense**
https://github.com/taiki-e/portable-atomic

Fixes #475

### CODE REVIEW

**Comment by djc** [comment]
I think you missed some imports in the `progress_bar` module?

**Comment by djc** [comment]
More in general, do you think it would be feasible to set something up in CI that would let us catch this?

**Comment by messense** [comment]
> I think you missed some imports in the `progress_bar` module?

`AtomicBool` isn't a problem and that was used only in tests, but to make it consistent I will change it.

**Comment by messense** [comment]
> More in general, do you think it would be feasible to set something up in CI that would let us catch this?

Added an armv5te test job using `cross`.

**Review by djc — APPROVED** [review]
This is great, thanks! @chris-laplante any thoughts?

**Comment by chris-laplante** [comment]
> This is great, thanks! @chris-laplante any thoughts?

Looks good to me!

**Review by chris-laplante — APPROVED** [review]

**Comment by messense** [comment]
Any chance to release a new version soon? Had to downgrade to 0.17 alpha releases to make it build on some 32-bit platforms.

**Comment by djc** [comment]
See #488.

**Pull request merged**
